// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package session

import (
	"context"
	"time"
)

// Service is a session storage service.
//
// It provides a set of methods for managing sessions and events.
type Service interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Delete(context.Context, *DeleteRequest) error

	// NOTE, my intention is to modify AppendEvent in my session/database implementation to support
	// 'user' sent partial messages, to build up a payload to go with their next message.
	// The idea is to collect user message parts and then include them in the next "real" AppendEvent.
	// Much like how multiple function calls can be executed in one message
	// 1. Coding assistant does work
	// 2. User makes edits            <== these become the partial events (user tool calls)
	// 3. User sends message,             the 'user' chat message becomes the last part, and does not have partial set
	// ... we need something for this
	// so AppendEvent will build up user message parts in the most recent 'user' event, until 'user' adds an event with !partial

	// AppendEvent is used to append an event to a session, and remove temporary state keys from the event.
	AppendEvent(context.Context, Session, *Event) error

	// Clone returns a copy of this session with a new ID
	// How this works is up to the implementation, some considerations
	// - many-to-many session-event (so they can share a history i.e. mainly to support trees and threads)
	// - if/how to track/manage lineage, where did we branch from & where is that stored on the new clone
	// even without many-to-many, like the current session/database impln, we could still walk lineage via state deltas
	Clone() (Session, error)

	// Splice makes in-place modifications to the session
	//   it is up to the user to manage state delta accumulation and handling (TODO, provide helpers)
	// insert: (N, 0, event)  | (N, 0, events)
	// delete: (N, 1, nil)    | (N, n, nil)
	// replace: (N, 1, event) | (N, n, events)
	// rewind: (len(session)-n, n, nil)
	// no-op: (N, 0, ...)
	Splice(start, count int, fill Events) (Session, error)
}

// InMemoryService returns an in-memory implementation of the session service.
func InMemoryService() Service {
	return &inMemoryService{
		appState:  make(map[string]stateMap),
		userState: make(map[string]map[string]stateMap),
	}
}

// CreateRequest represents a request to create a session.
type CreateRequest struct {
	AppName string
	UserID  string
	// SessionID is the client-provided ID of the session to create.
	// Optional: if not set, it will be autogenerated.
	SessionID string
	// State is the initial state of the session.
	State map[string]any
}

// CreateResponse represents a response for newly created session.
type CreateResponse struct {
	Session Session
}

// GetRequest represents a request to get a session.
type GetRequest struct {
	AppName   string
	UserID    string
	SessionID string

	// NumRecentEvents returns at most NumRecentEvents most recent events.
	// Optional: if zero, the filter is not applied.
	NumRecentEvents int
	// After returns events with timestamp >= the given time.
	// Optional: if zero, the filter is not applied.
	After time.Time
}

// GetResponse represents a response from [Service.Get].
type GetResponse struct {
	Session Session
}

// ListRequest represents a request to list sessions.
type ListRequest struct {
	AppName string
	UserID  string
}

// ListResponse represents a response from [Service.List].
type ListResponse struct {
	Sessions []Session
}

// DeleteRequest represents a request to delete a session.
type DeleteRequest struct {
	AppName   string
	UserID    string
	SessionID string
}
